language: node_js
sudo: false
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '6'
branches:
  only:
  - esa
env:
  global:
  - GIT_COMMITTER_NAME=ppworks
  - GIT_COMMITTER_EMAIL=koshikawa@ppworks.jp
  - GIT_AUTHOR_NAME=ppworks
  - GIT_AUTHOR_EMAIL=koshikawa@ppworks.jp
before_install:
- npm install
before_script:
- git config --global user.name 'ppworks'
- git config --global user.email 'koshikawa@ppworks.jp'
- rm -fr public
- git clone --depth=1 --branch=master https://github.com/ppworks/ppworks.github.io.git public
- cd public
- git ls-files | xargs -I {} rm -rf {}
- cd -
script:
- $(npm bin)/hexo generate
- cd public
- git add -A
- git commit -m 'Update'
- git push https://$GH_TOKEN@github.com/ppworks/ppworks.github.io.git master
